# Splunk Universal Forwarder - inputs.conf
# Place this file at:
# C:\Program Files\SplunkUniversalForwarder\etc\system\local\inputs.conf
# Then restart the forwarder: .\splunk.exe restart

[WinEventLog://Security]
index = main
disabled = false

[WinEventLog://System]
index = main
disabled = false

[WinEventLog://Application]
index = main
disabled = false

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
index = main
disabled = false
renderXml = true
